name: Main tests workflow

on: push
jobs:

  allure:
    steps:
      - name: Install Allure
        run: npm install -g allure-commandline
      - name: Run tests
        run: pytest --alluredir=allure-results
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
          allure open allure-report


