name: Main tests workflow

on: push
jobs:

  allure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install Allure
        run: npm install -g allure-commandline
      - name: Run tests
        run: pytest --alluredir=allure-results
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
          allure open allure-report


